sudo: false
os: linux

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

env:
  matrix:
    - JOB=1
    - JOB=2
    - JOB=3
    - JOB=4
    - JOB=5
    - JOB=6
    - JOB=7
    - JOB=8
    - JOB=9
    - JOB=10

script:
  - gcc-7 --version
